ColorRoomManager/Models/Material.cs
namespace ColorRoomManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Material
    {
        [Key]
        [StringLength(50)]
        public string MaterialCode { get; set; }

        [StringLength(255)]
        public string MaterialName { get; set; }

        public bool? IsActive { get; set; }

        [StringLength(20)]
        public string CreateBy { get; set; }

        public DateTime? CreateTime { get; set; }
    }
}

ColorRoomManager/Controllers/MaterialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ColorRoomManager.Models;

namespace ColorRoomManager.Controllers
{
    public class MaterialController : Controller
    {
        DBContext db = new DBContext();
        // GET: Material
        public ActionResult Index()
        {
            var lst = db.Materials.ToList();
            if (lst.Count > 0)
            {
                return View(lst);
            }
            return View();
        }

        public JsonResult MaterialAdd(Material models)
        {
            int status = 0;

            if (models != null)
            {
                var checkData = db.Materials.FirstOrDefault(x => x.MaterialCode == models.MaterialCode);
                if (checkData != null)
                {
                    status = -1;
                }

                Material material = new Material();
                material.MaterialCode = models.MaterialCode;
                material.MaterialName = models.MaterialName;
                material.IsActive = models.IsActive;
                material.CreateBy = User.Identity.Name;
                material.CreateTime = DateTime.Now;

                try
                {
                    db.Materials.Add(material);
                    db.SaveChanges();
                    status = 1;
                }
                catch (Exception ex)
                {
                    ex.ToString();
                }
            }
            return Json(status, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult MaterialUp(string Id)
        {
            var data = db.Materials.FirstOrDefault(x => x.MaterialCode == Id);
            if (data != null)
            {
                return PartialView("/Views/Material/_MaterialUp.cshtml", data);
            }
            //return View("Index");
            return RedirectToAction("Index");
        }

        public JsonResult MaterialUp(Material models)
        {
            bool status = false;

            if (models != null)
            {
                var data = db.Materials.FirstOrDefault(x => x.MaterialCode == models.MaterialCode);
                if (data != null)
                {
                    data.MaterialName = models.MaterialName;
                    data.IsActive = models.IsActive;
                    data.CreateBy = User.Identity.Name;
                    data.CreateTime = DateTime.Now;

                    try
                    {
                        db.SaveChanges();
                        status = true;
                    }
                    catch (Exception ex)
                    {
                        ex.ToString();
                    }
                }

            }
            return Json(status, JsonRequestBehavior.AllowGet);
        }

        public ActionResult MaterialDel(string Id)
        {
            var data = db.Materials.FirstOrDefault(x => x.MaterialCode == Id);
            if (data != null)
            {
                try
                {
                    db.Materials.Remove(data);
                    db.SaveChanges();
                }
                catch (Exception ex)
                {
                    ex.ToString();
                }
            }
            return RedirectToAction("Index");
        }
    }
}

ColorRoomManager/Views/Material/Index.cshtml
@model IEnumerable<ColorRoomManager.Models.Material>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    int i = 1;
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            <strong>MATERIALS</strong>
            <small>FVN</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Dashboard</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <p>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#color-add">
                Add new material
            </button>
        </p>

        <div class="row">
            <div class="col-md-12">
                <div class="box box-info">
                    <div class="box-header with-border">
                        <h3 class="box-title">Latest Orders</h3>

                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                                <i class="fa fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="table-responsive">
                            <table class="table no-margin">
                                <thead>
                                    <tr>
                                        <th>STT</th>
                                        <th>Material Code</th>
                                        <th>Material Name</th>
                                        <th>Status</th>
                                        <th>Chỉnh sửa</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null)
                                    {
                                        foreach (var item in Model)
                                        {
                                            <tr>
                                                <td><a href="#">@i</a></td>
                                                <td>@item.MaterialCode</td>
                                                <td>@item.MaterialName</td>
                                                <td>
                                                    <span class="label label-@(item.IsActive == true ? "success":"danger")">
                                                        @(item.IsActive == true ? "Hoạt động" : "Tạm khóa")
                                                    </span>
                                                </td>
                                                <td>
                                                    <a class="fa fa-edit btn-primary btn-sm" href="#" onclick="openModal('@item.MaterialCode')"></a>
                                                    <a class="fa fa-trash btn-danger btn-sm" href="@Url.Action("MaterialDel/"+ item.MaterialCode,"Material")" onclick="return confirm('Are you sure?')"> </a>
                                                </td>
                                            </tr>
                                            i++;
                                        }
                                    }
                                    else
                                    {
                                        <tr>
                                            <td colspan="5">
                                                <div class="alert alert-warning alert-dismissible">
                                                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                                    <h4><i class="icon fa fa-warning"></i> Thông báo!</h4>
                                                    <h3> Không tìm thấy dữ liệu !</h3>
                                                </div>
                                            </td>
                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                        <!-- /.table-responsive -->
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer clearfix">
                    </div>
                    <!-- /.box-footer -->
                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

@Html.Partial("_MaterialAdd")

<!-- #region Edit Operator -->
<div id='modal-edit' class='modal'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='ContentModal'></div>
        </div>
    </div>
</div>
<!-- #endregion -->

@section scripts {
    <script type="text/javascript">

        //Code cho function add new Operator
        function MaterialAdd() {
            var materialCode = $("#MaterialCode").val();
            var materialName = $("#MaterialName").val();
            var isActive = $("#isActive").is(":checked");
            var model = {
                'MaterialCode': materialCode,
                'MaterialName': materialName,
                'IsActive' : isActive,
            }; //End of model variable

            if (materialCode == null || materialCode == "" || materialName == null || materialName == "") {
                messages.notify("(*) - Requirement field", "error");
                return false;
            } //End of If statement
            else {
                $.ajax({
                    type: "POST",
                    url: "@(Url.Action("MaterialAdd", "Material"))",
                    content: "application/json; charset =utf-8",
                    dataType: "json",
                    data: model,
                    success: function (data) {
                        if (data == 1) {
                            messages.notify("Added an material successful!", "success");
                            window.location.reload();
                        } //End if Data == 1

                        if (data == -1) {
                            messages.notify("Data was existing!", "error");
                        } //End if Data == -1

                        if (data == 0) {
                            messages.notify("Error has occured while saving data!", "error");
                            return false;
                        } //End if Data == 0
                    }, //End of success function (data)
                    error: function (xhr, textStatus, errorThrown) {
                        messages.notify("Error has occured while saving data!", "error");
                        return false;
                    } //End of error function
                }); //End of ajax
            } //End of Else statement
        } //End function OperatorAdd

        //Code function Open modal
        var openModal = function (Id) {
            var url = '/Material/MaterialUp/' + Id;
            var options = { "backdrop": "static", keyboard: true };
            $.ajax({
                type: "GET",
                url: url,
                success: function (data) {
                    $('#ContentModal').html(data);
                    $('#modal-edit').modal(options);
                    $('#modal-edit').modal('show');
                }, //End function success
                error: function (e) {
                    return false;
                } //End function error
            }); //End ajax
        } //End function openModal

        //Code function edit an Operator
        function MaterialUp(Id) {
            var materialCode = $("#MaterialCodeUp").val();
            var materialName = $("#MaterialNameUp").val();
            var isActive = $("#isActiveUp").is(":checked");

            var model = {
                'MaterialCode': materialCode,
                'MaterialName': materialName,
                'IsActive': isActive,
            }; //End model

            if (materialCode == null || materialCode == "" || materialName == null || materialName == "") {
                messages.notify("(*) - Requirement field", "error");
                return false;
            } //End if
            else {
                $.ajax({
                    type: "POST",
                    url: "@(Url.Action("MaterialUp", "Material"))",
                    content: "application/json; charset =utf-8",
                    dataType: "json",
                    data: model,
                    success: function (data) {
                        if (data == 1) {
                            messages.notify("Edited an operator successfull!", "success");
                            window.location.reload();
                        }//End if data == 1
                        if (data == -1) {
                            messages.notify("Data was existing!", "error");
                        }//End if data == -1
                        if (data == 0) {
                            messages.notify("Error has occured while saving data!", "error");
                            return false;
                        }//End if data == 0
                    }, //End function success
                    error: function (xhr, textStatus, errorThrown) {
                        messages.notify("Error has occured while saving data!", "error");
                        return false;
                    }//End of function error
                }); //End ajax
            } //End of else
        } //End function edit an Operator
    </script>
}

ColorRoomManager/Views/Material/_MaterialAdd.cshtml
<div class="modal fade" id="color-add" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">Add new material</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label>Material code<code>(*)</code></label>
                    <input type="text" class="form-control" id="MaterialCode" name="MaterialCode" placeholder="Material code">
                </div>
                <div class="form-group">
                    <label>Material name<code>(*)</code></label>
                    <input type="text" class="form-control" id="MaterialName" name="MaterialName" placeholder="Material name">
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" id="isActive" name="isActive"> Active
                    </label>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="MaterialAdd(event)">Save changes</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

ColorRoomManager/Views/Material/_MaterialUp.cshtml
<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title">Update Material</h4>
    </div>
    <div class="modal-body">
        @if (Model != null)
        {
            <div class="form-group">
                <label>Material code<code>(*)</code></label>
                <input type="text" class="form-control" id="MaterialCodeUp" name="MaterialCodeUp" placeholder="Material code" value="@Model.MaterialCode" readonly>
            </div>
            <div class="form-group">
                <label>Material name<code>(*)</code></label>
                <input type="text" class="form-control" id="MaterialNameUp" name="MaterialNameUp" placeholder="Material name" value="@Model.MaterialName">
            </div>
            <div class="checkbox">
                <label>
                    <input type="checkbox" id="isActiveUp" name="isActiveUp" @(Model.IsActive == true ? "checked" : "")> Active
                </label>
            </div>
        }
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" onclick="MaterialUp('@Model.MaterialCode')">Save changes</button>
    </div>
</div>