ColorRoomManager/Models/Color.cs
namespace ColorRoomManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Color")]
    public partial class Color
    {
        [Key]
        [StringLength(50)]
        public string ColorCode { get; set; }

        [StringLength(255)]
        public string ColorName { get; set; }

        [StringLength(255)]
        public string ProductCode { get; set; }

        public bool? IsActive { get; set; }

        [StringLength(20)]
        public string CreateBy { get; set; }

        public DateTime? CreateTime { get; set; }
    }
}

ColorRoomManager/ViewModels/ColorViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ColorRoomManager.ViewModels
{
    public class ColorViewModels
    {
        public string ColorCode { get; set; }

        public string ColorName { get; set; }

        public string ProductCode { get; set; }

        public bool? IsActive { get; set; }

        public string CreateBy { get; set; }

        public DateTime? CreateTime { get; set; }
    }
}

ColorRoomManager/Controllers/ColorsController.cs
using ColorRoomManager.Models;
using ColorRoomManager.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ColorRoomManager.Controllers
{
    public class ColorsController : Controller
    {

        DBContext db = new DBContext();
        // GET: Colors
        public ActionResult Index()
        {
            var lst = db.Colors.ToList();
            if (lst.Count > 0)
            {
                return View(lst);
            }
            return View();
        }

        public JsonResult ColorAdd(ColorViewModels models)
        {
            int status = 0;
            if (models != null)
            {
                var checkData = db.Colors.FirstOrDefault(x => x.ColorCode == models.ColorCode);
                if (checkData != null)
                {
                    status = -1;
                }

                Color color = new Color();
                color.ColorCode = models.ColorCode;
                color.ColorName = models.ColorName;
                color.IsActive = models.IsActive;
                color.CreateBy = User.Identity.Name;
                color.CreateTime = DateTime.Now;

                try
                {
                    db.Colors.Add(color);
                    db.SaveChanges();
                    status = 1;
                }
                catch (Exception ex)
                {
                    ex.ToString();
                }
            }
            return Json(status, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ColorUp(string Id)
        {
            var data = db.Colors.FirstOrDefault(x => x.ColorCode == Id);
            if (data != null)
            {
                return PartialView("/Views/Colors/_ColorUp.cshtml", data);
            }
            //return View("Index");
            return RedirectToAction("Index");
        }

        public JsonResult ColorUp(ColorViewModels models)
        {
            bool status = false;

            if (models != null)
            {
                var data = db.Colors.FirstOrDefault(x => x.ColorCode == models.ColorCode);
                if (data != null)
                {
                    data.ColorName = models.ColorName;
                    data.IsActive = models.IsActive;
                    data.CreateBy = User.Identity.Name;
                    data.CreateTime = DateTime.Now;

                    try
                    {
                        db.SaveChanges();
                        status = true;
                    }
                    catch (Exception ex)
                    {
                        ex.ToString();
                    }
                }

            }
            return Json(status, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ColorDel(string Id)
        {
            var data = db.Colors.FirstOrDefault(x => x.ColorCode == Id);
            if (data != null)
            {
                try
                {
                    db.Colors.Remove(data);
                    db.SaveChanges();
                }
                catch (Exception ex)
                {
                    ex.ToString();
                }
            }
            return RedirectToAction("Index");
        }

    }
}

ColorRoomManager/Views/Colors/Index.cshtml
@model IEnumerable<ColorRoomManager.Models.Color>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    int i = 1;
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            <strong>COLORS</strong>
            <small>FVN</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Dashboard</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <p>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#color-add">
                Create Color
            </button>
        </p>
        <div class="row">
            <div class="col-md-12">
                <div class="box box-info">
                    <div class="box-header with-border">
                        <h3 class="box-title">Latest Orders</h3>

                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                                <i class="fa fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="table-responsive">
                            <table class="table no-margin">
                                <thead>
                                    <tr>
                                        <th>STT</th>
                                        <th>Color Code</th>
                                        <th>Color Name</th>
                                        <th>Status</th>
                                        <th>Chỉnh sửa</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null)
                                    {
                                        foreach (var item in Model)
                                        {
                                            <tr>
                                                <td><a href="#">@i</a></td>
                                                <td>@item.ColorCode</td>
                                                <td>@item.ColorName</td>
                                                <td>
                                                    <span class="label label-@(item.IsActive == true ? "success":"danger")">
                                                        @(item.IsActive == true ? "Hoạt động" : "Tạm khóa")
                                                    </span>
                                                </td>
                                                <td>
                                                    <a class="fa fa-edit btn-primary btn-sm" href="#" onclick="openModal('@item.ColorCode')"></a>
                                                    <a class="fa fa-trash btn-danger btn-sm" href="@Url.Action("ColorDel/"+ item.ColorCode,"Colors")" onclick="return confirm('Are you sure?')"> </a>
                                                </td>
                                            </tr>
                                            i++;
                                        }
                                    }
                                    else
                                    {
                                <tr>
                                    <td colspan="5">
                                        <div class="callout callout-warning">
                                            <h4>Warning!</h4>
                                            <p>
                                                <b>Data Not Found</b>&nbsp; Không có dữ liệu!
                                            </p>
                                        </div>
                                    </td>
                                </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                        <!-- /.table-responsive -->
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer clearfix">
                    </div>
                    <!-- /.box-footer -->
                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

@Html.Partial("_ColorAdd")

<!-- #region Edit MES WorkLoad -->
<div id='modal-edit' class='modal'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='ContentModal'></div>
        </div>
    </div>
</div>
<!-- #endregion -->

@section scripts {
    <script type="text/javascript">
        function ColorAdd() {
        var colorCode = $("#ColorCode").val();
        var colorName = $("#ColorName").val();
        var isActive =  $("#isActive").is(":checked");
        var model = {
            'ColorCode':colorCode,
            'ColorName':colorName,
            'IsActive': isActive,
        };
            if (colorCode == null || colorCode == "" || colorName == null || colorName == "") {
                messages.notify("Vui lòng điền đầy đủ các trường có(*)", "error");
            return false;
        }
        else {
            $.ajax({
            type: "POST",
                url: "@(Url.Action("ColorAdd", "Colors"))",
             content: "application/json; charset =utf-8",
            dataType: "json",
                data: model,
                success: function (data) {
                    if (data == 1) {
                        messages.notify("Thêm màu thành công!", "success");
                        window.location.reload();
                        }
                    if (data == -1) {
                     messages.notify("Dữ liệu đã tồn tại!", "error");
                     }
                    if (data == 0) {
                    messages.notify("Đã xảy ra lỗi trong quá trình lưu dữ liệu!", "error");
                    return false;
                    }
                  },
                    error: function (xhr, textStatus, errorThrown) {
                    messages.notify("Đã xảy ra lỗi trong quá trình lưu dữ liệu!", "error");
                            return false;
                        }
                    });
        }
        }

        var openModal = function (Id) {
              var url = '/Colors/ColorUp/' + Id;
            var options = { "backdrop": "static", keyboard: true };
            $.ajax({
                type: "GET",
                url: url,
                success: function (data) {
                    $('#ContentModal').html(data);
                    $('#modal-edit').modal(options);
                    $('#modal-edit').modal('show');
                },
                error: function (e) {
                    return false;
                }
            });
        }

        function ColorUp(colorCode) {
        var colorName = $("#ColorNameUp").val();
        var isActive =  $("#isActiveUp").is(":checked");
        var model = {
            'ColorCode':colorCode,
            'ColorName':colorName,
            'IsActive': isActive,
        };
            if (colorCode == null || colorCode == "" || colorName == null || colorName == "") {
                messages.notify("Vui lòng điền đầy đủ các trường có(*)", "error");
            return false;
        }
        else {
            $.ajax({
            type: "POST",
            url:"@(Url.Action("ColorUp", "Colors"))",
             content: "application/json; charset =utf-8",
            dataType: "json",
            data: model,
                success: function (data) {
                    if (data == 1) {
                        messages.notify("Thêm màu thành công!", "success");
                        window.location.reload();
                        }
                    if (data == -1) {
                     messages.notify("Dữ liệu đã tồn tại!", "error");
                     }
                    if (data == 0) {
                    messages.notify("Đã xảy ra lỗi trong quá trình lưu dữ liệu!", "error");
                    return false;
                    }
                  },
                    error: function (xhr, textStatus, errorThrown) {
                    messages.notify("Đã xảy ra lỗi trong quá trình lưu dữ liệu!", "error");
                            return false;
                        }
                    });
        }
        }
    </script>
}

ColorRoomManager/Views/Colors/_ColorAdd.cshtml
<div class="modal fade" id="color-add" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">Tạo màu</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label>Color code<code>(*)</code></label>
                    <input type="text" class="form-control" id="ColorCode" name="ColorCode" placeholder="Color code">
                </div>
                <div class="form-group">
                    <label>Color name<code>(*)</code></label>
                    <input type="text" class="form-control" id="ColorName" name="ColorName" placeholder="Color name">
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" id="isActive" name="isActive"> Active
                    </label>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="ColorAdd()">Save changes</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

ColorRoomManager/Views/Colors/_ColorUp.cshtml
<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title">Cập nhật màu</h4>
    </div>
    <div class="modal-body">
        @if (Model != null)
        {
            <div class="form-group">
                <label>Color code<code>(*)</code></label>
                <input type="text" class="form-control" id="ColorCodeUp" name="ColorCodeUp" placeholder="Color code" value="@Model.ColorCode" readonly>
            </div>
            <div class="form-group">
                <label>Color name<code>(*)</code></label>
                <input type="text" class="form-control" id="ColorNameUp" name="ColorNameUp" placeholder="Color name" value="@Model.ColorName">
            </div>
            <div class="checkbox">
                <label>
                    <input type="checkbox" id="isActiveUp" name="isActiveUp" @(Model.IsActive==true? "checked": "")> Active
                </label>
            </div>
        }
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" onclick="ColorUp('@Model.ColorCode')">Save changes</button>
    </div>
</div>