ColorRoomManager/Controllers/LossTypeController.cs
using ColorRoomManager.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ColorRoomManager.Controllers
{
    public class LossTypeController : Controller
    {
        DBContext db = new DBContext();
        // GET: LossType
        public ActionResult Index()
        {
            var lst = db.LossTypes.ToList();
            if (lst.Count > 0)
            {
                return View(lst);
            }
            return View();
        }

        public JsonResult LossTypeAdd(LossType models)
        {
            int status = 0;

            if (models != null)
            {
                var checkData = db.LossTypes.FirstOrDefault(x => x.Id == models.Id);
                if (checkData != null)
                {
                    status = -1;
                }

                LossType lossType     = new LossType();
                lossType.LossTypeName = models.LossTypeName;
                lossType.IsActive     = models.IsActive;
                lossType.CreateBy     = User.Identity.Name;
                lossType.CreateTime   = DateTime.Now;

                try
                {
                    db.LossTypes.Add(lossType);
                    db.SaveChanges();
                    status = 1;
                }
                catch (Exception ex)
                {
                    ex.ToString();
                }
            }
            return Json(status, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult LossTypeUp(int? Id)
        {
            var data = db.LossTypes.FirstOrDefault(x => x.Id == Id);
            if (data != null)
            {
                return PartialView("/Views/LossType/_LossTypeUp.cshtml", data);
            }
            //return View("Index");
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult LossTypeUp(LossType models)
        {
            bool status = false;

            if (models != null)
            {
                var data = db.LossTypes.FirstOrDefault(x => x.Id == models.Id);
                if (data != null)
                {
                    data.LossTypeName = models.LossTypeName;
                    data.IsActive     = models.IsActive;
                    data.CreateBy     = User.Identity.Name;
                    data.CreateTime   = DateTime.Now;

                    try
                    {
                        db.SaveChanges();
                        status = true;
                    }
                    catch (Exception ex)
                    {
                        ex.ToString();
                    }
                }

            }
            return Json(status, JsonRequestBehavior.AllowGet);
        }

        public ActionResult LossTypeDel(int? Id)
        {
            var data = db.LossTypes.FirstOrDefault(x => x.Id == Id);
            if (data != null)
            {
                try
                {
                    db.LossTypes.Remove(data);
                    db.SaveChanges();
                }
                catch (Exception ex)
                {
                    ex.ToString();
                }
            }
            return RedirectToAction("Index");
        }
    }
}

ColorRoomManager/Views/LossType/Index.cshtml
@model IEnumerable<ColorRoomManager.Models.LossType>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    int i = 1;
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            <strong>LOSS TYPE</strong>
            <small>FVN</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Dashboard</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <p>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#lossType-add">
                Create LossType
            </button>
        </p>

        <div class="row">
            <div class="col-md-12">
                <div class="box box-info">
                    <div class="box-header with-border">
                        <h3 class="box-title">Latest Orders</h3>

                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                                <i class="fa fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="table-responsive">
                            <table class="table no-margin">
                                <thead>
                                    <tr>
                                        <th>STT</th>
                                        <th>Loss Type Name</th>
                                        <th>Status</th>
                                        <th>Chỉnh sửa</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null)
                                    {
                                        foreach (var item in Model)
                                        {
                                            <tr>
                                                <td><a href="#">@i</a></td>
                                                <td>@item.LossTypeName</td>
                                                <td>
                                                    <span class="label label-@(item.IsActive == true ? "success":"danger")">
                                                        @(item.IsActive == true ? "Hoạt động" : "Tạm khóa")
                                                    </span>
                                                </td>
                                                <td>
                                                    <a class="fa fa-edit btn-primary btn-sm" href="#" onclick="openModal(@item.Id)"></a>
                                                    <a class="fa fa-trash btn-danger btn-sm" href="@Url.Action("LossTypeDel/"+ item.Id,"LossType")" onclick="return confirm('Are you sure?')"> </a>
                                                </td>
                                            </tr>
                                            i++;
                                        }
                                    }
                                    else
                                    {
                                <tr>
                                    <td colspan="5">
                                        <div class="callout callout-warning">
                                            <h4>Warning!</h4>
                                            <p>
                                                <b>Data Not Found</b>&nbsp; Không có dữ liệu!
                                            </p>
                                        </div>
                                    </td>
                                </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                        <!-- /.table-responsive -->
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer clearfix">
                    </div>
                    <!-- /.box-footer -->
                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

@Html.Partial("_LossTypeAdd")

<!-- #region Edit LossType -->
<div id='modal-edit' class='modal'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='ContentModal'></div>
        </div>
    </div>
</div>
<!-- #endregion -->

@section scripts {
    <script type="text/javascript">

        //Code cho function add new LossType
        function LossTypeAdd() {
            var lossTypeName = $("#lossTypeName").val();
            var isActive = $("#isActive").is(":checked");
            var model = {
                'LossTypeName': lossTypeName,
                'IsActive' : isActive,
            }; //End of model variable

            if (lossTypeName == null || lossTypeName == "") {
                messages.notify("(*) - Requirement field", "error");
                return false;
            } //End of If statement
            else {
                $.ajax({
                    type: "POST",
                    url: "@(Url.Action("LossTypeAdd", "LossType"))",
                    content: "application/json; charset =utf-8",
                    dataType: "json",
                    data: model,
                    success: function (data) {
                        if (data == 1) {
                            messages.notify("Added an lossType successful!", "success");
                            window.location.reload();
                        } //End if Data == 1

                        if (data == -1) {
                            messages.notify("Data was existing!", "error");
                        } //End if Data == -1

                        if (data == 0) {
                            messages.notify("Error has occured while saving data!", "error");
                            return false;
                        } //End if Data == 0
                    }, //End of success function (data)
                    error: function (xhr, textStatus, errorThrown) {
                        messages.notify("Error has occured while saving data!", "error");
                        return false;
                    } //End of error function
                }); //End of ajax
            } //End of Else statement
        } //End function LossTypeAdd

        //Code function Open modal
        var openModal = function (Id) {
            var url = '/LossType/LossTypeUp/' + Id;
            var options = { "backdrop": "static", keyboard: true };
            $.ajax({
                type: "GET",
                url: url,
                success: function (data) {
                    $('#ContentModal').html(data);
                    $('#modal-edit').modal(options);
                    $('#modal-edit').modal('show');
                }, //End function success
                error: function (e) {
                    return false;
                } //End function error
            }); //End ajax
        } //End function openModal

        //Code function edit an LossType
        function LossTypeUp(Id) {
            var lossTypeName = $("#lossTypeNameUp").val();
            var isActive = $("#isActiveUp").is(":checked");

            var model = {
                'Id': Id,
                'LossTypeName': lossTypeName,
                'IsActive': isActive,
            }; //End model

            if ( lossTypeName == null || lossTypeName == "") {
                messages.notify("(*) - Requirement field", "error");
                return false;
            } //End if
            else {
                $.ajax({
                    type: "POST",
                    url: "@(Url.Action("LossTypeUp", "LossType"))",
                    content: "application/json; charset =utf-8",
                    dataType: "json",
                    data: model,
                    success: function (data) {
                        if (data == 1) {
                            messages.notify("Edited an lossType successfull!", "success");
                            window.location.reload();
                        }//End if data == 1
                        if (data == -1) {
                            messages.notify("Data was existing!", "error");
                        }//End if data == -1
                        if (data == 0) {
                            messages.notify("Error has occured while saving data!", "error");
                            return false;
                        }//End if data == 0
                    }, //End function success
                    error: function (xhr, textStatus, errorThrown) {
                        messages.notify("Error has occured while saving data!", "error");
                        return false;
                    }//End of function error
                }); //End ajax
            } //End of else
        } //End function edit an LossType
    </script>
}

ColorRoomManager/Views/LossType/_LossTypeAdd.cshtml
<div class="modal fade" id="lossType-add" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">Create step</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label>Loss type name<code>(*)</code></label>
                    <input type="text" class="form-control" id="lossTypeName" name="lossTypeName" placeholder="Loss type name">
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" id="isActive" name="isActive"> Active
                    </label>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="LossTypeAdd()">Save changes</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

ColorRoomManager/Views/LossType/_LossTypeUp.cshtml
<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title">Loss Type Edit</h4>
    </div>
    <div class="modal-body">
        @if (Model != null)
        {
            <div class="form-group">
                <label>Step name<code>(*)</code></label>
                <input type="text" class="form-control" id="lossTypeNameUp" name="LossTypeNameUp" placeholder="Loss type name" value="@Model.LossTypeName">
            </div>
            <div class="checkbox">
                <label>
                    <input type="checkbox" id="isActiveUp" name="isActiveUp" @(Model.IsActive == true ? "checked" : "")> Active
                </label>
            </div>
        }
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" onclick="LossTypeUp('@Model.Id')">Save changes</button>
    </div>
</div>